---
development:
  cloud_name: hapokmute
  api_key: '362222546174156'
  api_secret: Q8C5VEuEu5W_qabMQyrSsbzQuA8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hapokmute
  api_key: '362222546174156'
  api_secret: Q8C5VEuEu5W_qabMQyrSsbzQuA8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hapokmute
  api_key: '362222546174156'
  api_secret: Q8C5VEuEu5W_qabMQyrSsbzQuA8
  enhance_image_tag: true
  static_file_support: false
